#define BYTE_END '#'
#define NULL_ADD '@'

#define BYTE_PUSH_Q 'A'
#define BYTE_PUSH_R 'B'
#define BYTE_PUSH_MR 'C'
#define BYTE_PUSH_MRQ 'D'
#define BYTE_POP 'E'
#define BYTE_IN 'F'
#define BYTE_OUT 'G'
#define BYTE_CALL 'H'
#define BYTE_POP_MR 'I'

#define BYTE_ADD '+'
#define BYTE_SUB '-'
#define BYTE_MUL '*'
#define BYTE_DIV '/'

#define BYTE_RET 'J'

#define BYTE_JMP 'j'
#define BYTE_JA 'a'
#define BYTE_JB 'b'
#define BYTE_JE 'e'

#define BYTE_REG_RAX 'k'
#define BYTE_REG_RBX 'l'
#define BYTE_REG_RCX 'm'
#define BYTE_REG_RDX 'n'
#define BYTE_REG_RSI 'o'
#define BYTE_REG_RDI 'p'
#define BYTE_REG_RSP 'q'
#define BYTE_REG_RBP 'r'
#define BYTE_REG_R9 's'
#define BYTE_REG_R10 't'
#define BYTE_REG_R11 'u'
#define BYTE_REG_R12 'v'
#define BYTE_REG_R13 'w'
#define BYTE_REG_R14 'x'
#define BYTE_REG_R15 'y'
